# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

services:
  rest_bank_app:
    build:
      context: .
    container_name: rest_bank_app
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - 'DB_HOST=postgres'
      - 'DB_PORT=5432'
      - 'DATABASE_NAME=bank_db'
      - 'DB_USER=user'
      - 'DB_PASS=secret'

  postgres:
    image: 'postgres:18'
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "user"
      POSTGRES_DB: "bank_db"
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
