#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/migration/db.changelog.yaml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE_NAME:bank_db}
    username: ${DB_USER:user}
    password: ${DB_PASS:secret}
    driver-class-name: org.postgresql.Driver

application:
  security:
    data-encoding:
      card-number-secret-key: "X3VrayyT8qL9x/d3Ie+XbA0/a/p8c/N6Z/R4g7I9b0w="
      refresh-token-secret-key: "aBc/dEfGhIjKlMnOpQrStUvWxYz12345aBcDeFgH6iI="
    jwt:
      expires-in-millis: 720000_0
      singing-key: "b73a2e57e30f14b839ba7ca4fc353d43dde7a56e3ca9b6a9b71b9e289883f3da72d77851c2bfb522f0ecfe58e9fb6eb28158114befa99dd5f07206f52a927cf614d84c0d0424a745d7ec619848cf2cddbda8b218d886270d9264c1bf9bbb5b421bad3d713f94f42c2c6b1a1b1b64ea26c34a85cc205f2ed33ffb03c5f88032bfa3495dcc2e61f002b2ad61c33126c266b97e2b91a83baf55970542770a1b81833945466792b525370fcc63d369dedcff0672919451627c03df830032de523b20ea28c12947452850d5f6f8e1cf0253bc3660f17a2741702b7640cfa10661684bf49fde6f14ed6312c82005f55ee62e4ff7ba8e3223abb9a899bcfe44c2a9486e"


